name: C++

on:
  push:
<<<<<<< HEAD
    branches: [master]
=======
    branches: [main]
>>>>>>> 5a3efaee (Update cpplint command)
  pull_request:

permissions:
  contents: read

jobs:
  format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install dos2unix
        run: sudo apt-get install -y dos2unix

      - name: Check formatting
        run: ./format.sh && git diff --exit-code

  cpplint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Install cpplint
        run: pip install cpplint

      - name: Run lint
        run: cpplint --recursive .
